# Numpy 

- Range

In [13]:
# example 1
range(0, 5)

# wont work cause we need to range in a list 

range(0, 5)

In [14]:
#  with list 

list(range(0,5))

#  this ranges numbers form 0 to 5

[0, 1, 2, 3, 4]

In [15]:
# lets try to perform an arithemetic operattion to multiply to arrays /

list1 = [1, 3, 5, 7, 9]
list2 = [2, 4, 6, 8, 10]

list1 * list2

# this will give us an error

TypeError: can't multiply sequence by non-int of type 'list'

- NOW LETS INTRODUCE NUMPY 

In [ ]:
#  WE WILL DEFINE SOME TYPE OF VARIABLE 
#  first import numpy library

import numpy as np


In [ ]:
x = np.array([1, 3, 5, 7, 9])
y = np.array([2, 4, 6, 8, 10])

x * y

#  there we have performed an arithemetic operation 

array([ 2, 12, 30, 56, 90])

In [ ]:
#  if we want to check out the type 
print(type(x))
print(type(y))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
# define a variable 
variable_1 = np.array([2,4,6,8,10])
variable_1

array([ 2,  4,  6,  8, 10])

In [ ]:
# we can print the variable type 

print(type(variable_1))

<class 'numpy.ndarray'>


In [ ]:
# numpy zeros function

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
# now as a matrix like 3 by 5 

np.zeros((3,5), dtype=int)


# NOTE WHEN WE ARE DEFINING THE MATRIX WE CAN US E THE (())

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [16]:
# With ones 

np.ones((3,4,5), dtype=int)

# NOTE THE 3 DEFINES THE NUMBER OF MATRIXS 

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [17]:
import numpy as np
np.full(8, 5)

# here "8" is like the number of times that "5" ahs to appear

array([5, 5, 5, 5, 5, 5, 5, 5])

In [21]:
# 2D Array
np.full((2, 3),5,  dtype="float")

# here (2,3) are the rows and columns of the 2D matrix and "5" is the matrix element

array([[5., 5., 5.],
       [5., 5., 5.]])

In [22]:
# LINSPACE 

import numpy as np


In [24]:
lins_space = np.linspace(10,30, 11, dtype=int)
lins_space


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [30]:
#  a matrics
lins_space = np.linspace(10, 30, 11,  dtype=int)
lins_space

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [39]:
# rand 
# make an array 

random_1 =np.random.rand(2,5)
random_1

array([[9.88471058e-01, 3.32581483e-01, 5.63346408e-04, 8.47340406e-01,
        1.05999388e-01],
       [4.46729912e-01, 8.19740277e-01, 7.43161341e-01, 5.50028246e-01,
        1.51469200e-02]])

In [47]:
# rand 
# make ajust returns a value etc 

random_1 =np.random.randint(2,6)
random_1



5

In [49]:
#  in matrix mode

arrayMax2 = np.random.randint(0, 50, (4, 5))
arrayMax2

# here is a matrix of number 0to 50 in a 4by 5 matrix etc


array([[42, 11, 34,  5, 35],
       [38, 40, 12, 12,  0],
       [10, 29, 40, 13,  1],
       [ 6,  3, 17, 36,  0]])

In [50]:
# EXAMPLE 1

import numpy as np

arraySlip1 = np.array([1, 3, 5, 50, 2, 4, 6,])
arraySlip1

array([ 1,  3,  5, 50,  2,  4,  6])

In [51]:
# say we want to slit the array
np.split(arraySlip1, [3, 5])

# what this basically does is that it gets one array into equal parts
# in this arrary "3" is the the lenth of the first array we want cause there are "7" elememnts, "5" is divided into what is possible

[array([1, 3, 5]), array([50,  2]), array([4, 6])]

In [52]:
# EXAMPLE 1

import numpy as np

arraySlip1 = np.array([1, 3, 5, 50, 2, 4, 6, 8,10])
arraySlip1

array([ 1,  3,  5, 50,  2,  4,  6,  8, 10])

In [56]:
# say we want to slit the array
np.split(arraySlip1, [4, 7])

# what this basically does is that it gets one array into equal parts
# in this arrary "3" is the the lenth of the first array we want cause there are "7" elememnts, "5" is divided into what is possible

[array([ 1,  3,  5, 50]), array([2, 4, 6]), array([ 8, 10])]

In [57]:
# example
#  lets just create a random array

Vsplit = np.arange(8).reshape(2, 4)
Vsplit

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [58]:
# we use the hsplit
np.hsplit(Vsplit, 4)

[array([[0],
        [4]]),
 array([[1],
        [5]]),
 array([[2],
        [6]]),
 array([[3],
        [7]])]

In [59]:
# example1
import numpy as np

exampleSort = np.random.randint(2, 20, 11)
exampleSort

array([ 6,  9,  2,  4, 17, 19,  9, 11,  8, 16, 19])

In [60]:
#  now lets use the sort function to rewrite this array
np.sort(exampleSort)

array([ 2,  4,  6,  8,  9,  9, 11, 16, 17, 19, 19])

In [1]:
sales_record = {
    'price': 3.24,
    'num_items': 4,
    'person': 'Chris'
}


sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'

print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))


Chris bought 4 item(s) at a price of 3.24 each for a total of 12.96


<br>
# Reading and Writing CSV files

<br>
Let's import our datafile mpg.csv, which contains fuel economy data for 234 cars.

* mpg : miles per gallon
* class : car classification
* cty : city mpg
* cyl : # of cylinders
* displ : engine displacement in liters
* drv : f = front-wheel drive, r = rear wheel drive, 4 = 4wd
* fl : fuel (e = ethanol E85, d = diesel, r = regular, p = premium, c = CNG)
* hwy : highway mpg
* manufacturer : automobile manufacturer
* model : model of car
* trans : type of transmission
* year : model year

In [2]:
import csv

%precision 2

with open('materials/mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    
mpg[:3] # The first three dictionaries in our list.

FileNotFoundError: [Errno 2] No such file or directory: 'materials/mpg.csv'